tleunen/babel-plugin-module-resolver

- README.md
- package.json
- src/index.js
Currently it's impossible to alias a single module instead of the folder. This PR removes one of the checks allowing you to do so.
> Added support for single-module alias.

- src/index.js
- test/index.js
We've been trying to use this plugin with projects that use [AVA](http://ava.li) for testing.
AVA uses child processes and sets `cwd` to the directory of the current test file. Thus, `state.file.opts.filename` would be an absolute path and the plugin wouldn't map the module correctly.
This PR is an attempt to fix that issue.
> Can map for process that changes cwd.

- src/index.js
Windows does not always have an environment variable named PWD.  If it is not present, it seems safe to just resolve relative to the true current working directory.
> Fix windows support

- .editorconfig
- .eslintrc
- README.md
- codecov.yml
- package.json
- src/index.js
- src/mapToRelative.js
- test/index.js
- test/mapToRelative.js
Fixes #46
BREAKING CHANGE: There's a new way to specify alias in the plugin options.
> feat: Add support for custom root directories

- README.md
- package.json
- src/index.js
- test/index.js
Fixes #70 
cc @kellyrmilligan
This should resolve your issue :)
These extensions `['.js', '.jsx', '.es', '.es6']` will be handled by default, because these are the ones Babel handle. But I also added a new setting to set any custom extension.
> Fix root mapping with custom extensions

- README.md
- src/index.js
- src/mapToRelative.js
- test/index.js
The `npm:` prefix wasn't really necessary because we can detect if the final path is a local file (starting with a dot), or a path to a npm module.
The following example will redirect all underscore calls to lodash.
```json
{
"alias": {
"underscore": "lodash"
}
}
```
> feat: Aliasing a npm module without 'npm:'

- src/index.js
- test/index.js
Fixes #74 
Checking the extension of the source file and the real file allows us to verify it's a real extension of something from the filename.
> fix: Fix resolver with filename containing a dot

- README.md
- appveyor.yml
This adds Appveyor so we can make sure the plugin works in a Windows environment
Related to https://github.com/tleunen/babel-plugin-module-resolver/issues/77
> chore: Add appveyor CI

- .eslintrc
- package.json
- src/index.js
- src/mapToRelative.js
- test/index.js
- test/mapToRelative.js
Fixes #61 
Hey @danez and @valerybugakov, can I ask you to try this fix and let me know if this resolves your issues? :)
For every file, I now get the closest babel config file to calculate the relative paths based on it instead of the working directory (which could be different).
> fix: Use the a working directory based on the closed babelrc config file

- src/index.js
`this` contexts of `manipulateOptions` and `pre` are not the same, so option `cwd` was being ignored.
Also, the param `file` needed to be resolved absolutely before all the logic.
I guess now we really can use this plugin with a `.babelrc` in a different directory than cwd.
> Fix "cwd" option being ignored and file resolving

- src/index.js
- test/index.test.js
- test/jest.test.js
Add support to update the paths for the specifics Jest function `mock`, `unmock` and `genMockFromModule`.
Closes #97
> feat: Add support for Jest specific functions

- src/index.js
- test/system.test.js
> feat: Add support for System.import

- src/index.js
Required to be able to fix this issue in the eslint plugin: https://github.com/tleunen/eslint-import-resolver-babel-module/issues/42
It also means there's potentially another issue here, since we need to know the cwd to compute the root paths, but we can determine the real cwd only once we start parsing a file. So the used cwd in `manipulateOptions` might not always be the right one. (eg project root instead of being the babelrc root, which might be a subdirectory of the project root)
@fatfisz Any idea?
In the short term, it should fix the initial issue with sublime, but it'll be great to find a solution to this cwd
> Fix root globbing cwd in Sublime

- src/getRealPath.js
This quickfix should resolve the `Cannot read property 'find' of undefined` error a few users have.
I'll need to investigate further to better understand why in some cases, `regExps` is not set.
> fix: Fix `regExps.find` undefined error

- src/getRealPath.js
- src/index.js
- test/index.test.js
This reverts the change in 217120065e5dbe13f6671c8bca4212cf42fe5279, because it si not covered by any tests. If `getRealPath` should handle unparsed options, then I'd at least like to add some tests.
> Fix the double plugin bug

- src/index.js
- test/index.test.js
- test/jest.test.js
- test/system.test.js
fix issue https://github.com/tleunen/babel-plugin-module-resolver/issues/152,
> Convert root to array if root is a string #152

- .eslintrc.js
- src/getRealPath.js
- src/index.js
Those are some additional changes for the bug fix that I had in my repo. Mostly refactoring, no behavior changed (tests are intact).
Notable change: the `no-param-reassign` rule was disabled inline so many times that it made sense to allow it in the configuration - only for property assignment, not arguments themselves (they are like `const` values now).
> Refactor options preprocessing

- src/getRealPath.js
- src/index.js
- src/mapToRelative.js
- test/index.test.js
This is actually a bugfix - the cwd was being used too late, after resolving the glob pattern. If it is done before, the glob package will look for resolved paths in the right directory from the start.
> Fix: use the cwd option for glob patterns

- .babelrc
Rollup is great: it reduces the number of `require` calls and produces a clean output, while putting all of the modules in the same scope.
I've also set the "loose" option for babel plugins for a cleaner output.
> Chore: specify more loose options for babel

- src/getRealPath.js
- src/index.js
- src/normalizeOptions.js
- src/transformers/call.js
- src/transformers/import.js
- src/utils.js
- test/index.test.js
This is the last one of my refactors. Changes here:
- moving `normalizeOptions` to a separate file, which separates it from the visitor code. Makes the intent in `index.js` more clear IMO, because there is a lot less to look at now.
- making resolvers into a pipeline-ish thing: there was a pattern which was repeated three times and so it made sense to let JS go over the resolvers in the right order (a bit more clear now - one array with all of them) instead of repeating the code.
- moving `types` into state - a thing I experimented with in another plugin. It allows moving the visitor code out of the main export function, which I also did.
- adding more tests for yet undocumented scenarios.
Edit: added the point about `types`.
Edit: added the point about the tests.
> Chore: refactor normalizeOptions and the resolver pipeline

- src/normalizeOptions.js
- test/index.test.js
I noticed it by an accident, but it seems fairly serious. There were no tests for this.
For example if an alias exists for `components`, then `components_dummy` should not be aliased, only `components` or `components/*`.
> Fix a case when the alias is not a proper sub path

- .gitignore
- src/getRealPath.js
- src/utils.js
- test/index.test.js
There were problems described e.g. in #167 wrt. the possible double application stemming from a not-exactly-good configuration. I think we should warn when this _may_ happen and consider this an anti-pattern.
Example of such configuration:
```
alias: {
'react-native-vector-icons': '@expo/vector-icons',
'@expo/vector-icons/lib/create-icon-set': 'react-native-vector-icons/lib/create-icon-set',
'@expo/vector-icons/lib/icon-button': 'react-native-vector-icons/lib/icon-button'
}
```
If there's a path `react-native-vector-icons/lib/create-icon-set` then first application of the plugin will transform it to `@expo/vector-icons/lib/create-icon-set`, and another application will result in `react-native-vector-icons/lib/create-icon-set`. This is actually causing trouble for users in some cases.
--- …
> Prevent double application of the transform

- README.md
- src/normalizeOptions.js
- src/utils.js
- test/index.test.js
Adds the `getRealPath` option, thus solving the #165 issue.
I used the `getRealPath` name, but maybe just `transform` would be good? But then `getRealPath` is exposed in the module... I just have a tiny doubt about the name. Maybe it would be good to instead expose `transform` and use that instead of `getRealPath` consistently.
I'm marking this as WIP because it depends on the changes from #194.
> Add the resolvePath option

- README.md
- src/resolvePath.js
- src/utils.js
- test/index.test.js
See #90 for context.
Example : 
```json
#before.babelrc
{
"presets": ["react-native"],
"plugins": [
[
"module-resolver",
{
"root": ["./src"],
"extensions": [".js", ".ios.js", ".android.js"]
}
]
]
}
#after.babelrc
{
"presets": ["react-native"],
"plugins": [
[
"module-resolver",
{
"root": ["./src"],
"extensions": [".js", ".ios.js", ".android.js"],
"stripExtensions": [".ios.js", ".android.js"]
}
]
]
}
````
```javascript
/*
- module
- index.ios.js
- index.android.js
*/
// Before 
import module from 'module'; // -> import module from './module/index.ios';
// After
import module from 'module'; // -> import module from './module';
```
We let the RN packager to choose which file to import depending on the platform.
> Add a stripExtensions option for RN support

- src/resolvePath.js
- test/index.test.js
Following this https://github.com/tleunen/babel-plugin-module-resolver/pull/218
BREAKING CHANGE: This makes alias taking precedence over the root config because it's usually more specific. It might break for some users. Although, I don't think most users will be affected by this.
> feat: Make alias config take precedence over root config

- src/index.js
In both [babel 6](https://github.com/babel/babel/blob/6.x/packages/babel-core/src/transformation/plugin.js#L16) and [babel 7](https://github.com/babel/babel/blob/master/packages/babel-core/src/config/plugin.js#L34) the key is set to the name if the plugin defines one.
As the eslint resolver is now checking for [the key](https://github.com/tleunen/eslint-import-resolver-babel-module/blob/master/src/index.js#L26) it is important to set the name here.
Currently only babel-configs work that reference the plugin with `'module-resolver'`.
With this change it does not matter how the plugin is used in the config (`require`, `require.resolve`, `'babel-plugin-module-resolver'`) as the key will always be set to the name.
Fixes tleunen/eslint-import-resolver-babel-module#70
> Set name of plugin for eslint integration

- src/normalizeOptions.js
- test/call.test.js
http://facebook.github.io/jest/docs/en/jest-object.html#jestsetmockmodulename-moduleexports
> Add jest.setMock to the list of transformed jest functions

- package.json
- src/index.js
- src/normalizeOptions.js
- test/call.test.js
>  Add require.requireActual and require.requireMock to the list of transformed Jest functions

- DOCS.md
- README.md
Thanks for the plugin.
It's been really helpful for me! I thought I'd start restructuring slightly the documentation after I saw #216 
I extracted everything in a file `DOCS.md`. Added a more structure hierarchy with links pointing to the different sections.
Tried to add examples where I could. 
That is far from perfect but I believe that it is a first step. Let me know if you'd like me to change anything.
> Improve documentation and README.md readibility

- src/normalizeOptions.js
- test/index.test.js
- test/normalizeOptions.test.js
Introduced an option to declare the `alias` property as an array, which would allow the correct enumeration order of the aliases. The current implementation is preserved, so both ways are going to work:
```
"alias": {
"foo": "A",
"bar": "B",
"baz": "C"
}
```
and:
```
"alias": [
{
"foo": "A",
"bar": "B",
},
{ "baz": "C" }
]
```
Reference: https://github.com/tleunen/babel-plugin-module-resolver/issues/238
> Ability to declare aliases in an array

- DOCS.md
- src/normalizeOptions.js
- test/index.test.js
This implements a feature requested in #242.
> Allow passing a function as a RegExp substitute

- DOCS.md
- src/normalizeOptions.js
- src/resolvePath.js
- src/utils.js
- test/index.test.js
Add stripExtensions option to determine which extensions get removed.
Also process relative paths so that extensions get resolved.
> Add stripExtensions option to determine which extensions get removed.

- src/resolvePath.js
- src/utils.js
- test/index.test.js
Currently the code checks for a relative path by checking if it starts with a dot. This incorrectly identifies a path resolved dot file e.g. `.eslintrc` as a relative path. So it does NOT transform the path to relative path such as `./.eslintric`. This is fixed by using a regex that checks for a `./` or `../` at the start of the path.
> Fix path transformation for dot files that are sibling to current file

- DOCS.md
The two third-level headings in `DOCS.md` aren't formatted correctly because of non-breaking space characters (`U+00A0`) after `###`.
> Fix space characters in third-level headings

- src/index.js
- src/transformers/call.js
- src/transformers/import.js
- test/dynamicImport.test.js
We have the usecase that one of our own transforms adds dynamic imports with paths which need to be replaced by this plugin.
This wasn't working because this plugin is run on Program:enter before all other plugins are executed.
I changed it so that the plugin now runs on both enter and exit to handle both of the usecases:
- Other plugin wants to resolve/use path to module from import/require (needs replacement happen before -> `Program:enter`)
- Other plugin inserts a new import/require (needs replacement happen afterwards -> `Program:exit`)
In order to avoid double transformation I added a list of already visited paths, so that each path only gets visited/transformed once.
> Run plugin also on Program:exit

- .babelrc
- .circleci/config.yml
- appveyor.yml
- package.json
> Re-vert to Node.js v4

- .circleci/config.yml
- appveyor.yml
- package.json
It seems that the current AppVeyor config is broken because npm received an upgrade which breaks the build (and it shouldn't). The culprit is the line which installs the latest version of npm (while being used e.g. with node 4). It might be worth to make the config future-proof instead.
> Fix AppVeyor config + drop support for node 4

- DOCS.md
Related to #297, apparently with Babel 7 (which will land with next version of RN) the order or the extensions "matters" so better to suggest the correct order in the DOC
> Fix order for React Native

- README.md
Hello!
Your library is great! I created an ESLint plugin to work with your module. I find that team members may not be aware of the aliases, so to keep everyone on the same page this rule will warn when aliased modules are being pulled in using relative paths. https://github.com/HeroProtagonist/eslint-plugin-module-resolver. Feel free to close this PR if you do not want it in, but thought others may find it useful.
Thanks!
> Add eslint-plugin-module-resolver link to readme

- src/normalizeOptions.js
- src/utils.js
- test/index.test.js
Closes #312 
(See #312 for detailed explanation)
> Escape key of alias to support using $ prefix

- DOCS.md
Thanks for maintaining this library! This makes it easier to find the section on usage with Create React App.
> Add a direct link to create-react-app in the docs.

- README.md
added an example for js version of the configuration.
Babel 7 came with big changes and internet is full of with old version examples. 
I think it'll be a good idea to have it at your Readme. Please request changes if something wrong
> Docs: .babelrc.js example added

- .babelrc
3.1.2 has introduced breaking change (requiring `core-js`) which was caused by migration from babel@6 to babel@7 and using different option for the `useBuiltIns` option of preset-env (with different semantics than previously)
https://babeljs.io/docs/en/6.26.3/babel-preset-env#usebuiltins
https://babeljs.io/docs/en/babel-preset-env#usebuiltins-entry
Fixes #349
> Remove unused "useBuiltIns" option from @babel/preset-env (which has unexpected behaviour for our case anyway)

- DOCS.md
- src/normalizeOptions.js
- src/resolvePath.js
- test/index.test.js
- Add `loglevel` option
- Disable missing path warning if `loglevel` is `"silent"`
We use this plugin to export a "virtual dependency" in our published modules, so that consumers of our module can override a deep dependency. We then alias the virtual module in Webpack config, not babel config. So we expect the virtual module not to exist at Babel build time.
Your plugin works great (thank you!) but it logs a lot of warnings due to our configuration, so we'd appreciate this option to quiet them.
> feat(dev): add loglevel to configure console logging

- README.md
> chore: Update Expo link

- README.md
After almost an hour of searching I finally found a workaround for custom aliases in Webstorm: Adding a webpack config file to intellij / Webstorm will enable correct highlighting. I'd like this to be documented in the README.md so other people don't have to waste their time.
> update readme to include Intellij / Webstorm workaround for resolving aliases

- src/normalizeOptions.js
- test/call.test.js
Newer versions of jest use `jest.requireActual` and `jest.requireMock` instead of `require.requireActual` and `require.requireMock`
> Add new jest methods

- DOCS.md
- README.md
As it is if you click on the GitHub markdown copy button on the right you have to then manually remove the $.
> Valid install commands when using Github copy button

- .babelrc
- .github/workflows/test.yml
- appveyor.yml
- package-lock.json
- package.json
- src/resolvePath.js
- test/index.test.js
This update all dependencies, but especially find-babel-config which fixes a json5 vulnerability.
BREAKING CHANGES: Remove support for Node < 16
> chore: Update dependencies

- test/index.test.js
Some tests are skipped, this change allows to launch all the tests by removing the `only` keyword
> fix(tests): run all tests
